In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../dataset/raw_dataset.csv")

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df.head()

,Call_ID,Call_Timestamp,Patient_Age,Patient_Gender,State,Language,New_or_Existing_Patient,Call_Channel,Caller_Relationship,Chief_Complaint,Symptoms_Reported,Symptom_Severity,Duration_of_Symptoms_Days,Pain_Score,Emergency_Flag,Chronic_Condition,Insurance_Type,Preferred_Appointment_Urgency,Prior_Hospital_Visit_30D,Call_Duration_Minutes,Wait_Time_Minutes,Repeat_Caller,Sentiment,Call_Transcript_Summary,Recommended_Department
0,CALL-0000001,2025-02-27 20:09:18,33,Female,Alaska,English,Existing,Phone,Self,Needs to see a doctor and agent every,mild fever; blood pressure follow-up; general ...,High,10,9,No,Hypertension,Medicaid,Immediate,Yes,17,1,No,Anxious,Caller reached the hospital call center genera...,Primary Care
1,CALL-0000002,2025-06-27 20:33:38,27,Male,Louisiana,English,Existing,Phone,Self,"Caller reports abdominal pain, vomiting",abdominal pain; vomiting; acid reflux,Low,21,6,No,NaN,Private,Routine,No,9,5,No,Calm,Family member called the access center stomach...,Gastroenterology
2,CALL-0000003,2026-01-09 06:34:10,38,Male,Arizona,English,New,Phone,Caregiver,"Caller reports needs specialist slot, book app...",needs specialist slot; book appointment,Medium,14,3,No,NaN,Private,Routine,No,11,3,No,Anxious,Caller reached the hospital call center appoin...,Scheduling
3,CALL-0000004,2025-09-01 10:33:37,7,Female,Connecticut,English,Existing,Phone,Parent,"Patient is dealing with skin lesion, acne flare",skin lesion; acne flare,Low,93,1,No,Multiple,Medicaid,Soon,No,25,9,No,Distressed,Family member called the access center dermato...,Dermatology
4,CALL-0000005,2024-10-07 16:00:57,17,Male,Iowa,English,Existing,Phone,Self,"Parent says child has fatigue, weight loss",fatigue; weight loss,Medium,83,3,No,Multiple,Private,Soon,Yes,12,9,No,Distressed,Family member called the access center oncolog...,Pediatrics

In [5]:
print(df.shape)
print(df.info())
print(df.isnull().sum())
print(df["Recommended_Department"].unique())
print(df["Recommended_Department"].value_counts())

(10000, 25)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Call_ID                        10000 non-null  object
 1   Call_Timestamp                 10000 non-null  object
 2   Patient_Age                    10000 non-null  int64
 3   Patient_Gender                 10000 non-null  object
 4   State                          10000 non-null  object
 5   Language                       10000 non-null  object
 6   New_or_Existing_Patient        10000 non-null  object
 7   Call_Channel                   10000 non-null  object
 8   Caller_Relationship            10000 non-null  object
 9   Chief_Complaint                10000 non-null  object
 10  Symptoms_Reported              10000 non-null  object
 11  Symptom_Severity               10000 non-null  object
 12  Duration_of_Symptoms_Days      10000 non-null  int64
 13  Pain_Score                     10000 non-null  int64
 14  Emergency_Flag                 10000 non-null  object
 15  Chronic_Condition              5806 non-null   object
 16  Insurance_Type                 10000 non-null  object
 17  Preferred_Appointment_Urgency  10000 non-null  object
 18  Prior_Hospital_Visit_30D       10000 non-null  object
 19  Call_Duration_Minutes          10000 non-null  int64
 20  Wait_Time_Minutes              10000 non-null  int64
 21  Repeat_Caller                  10000 non-null  object
 22  Sentiment                      10000 non-null  object
 23  Call_Transcript_Summary        10000 non-null  object
 24  Recommended_Department         10000 non-null  object
dtypes: int64(5), object(20)
memory usage: 1.9+ MB
None
Call_ID                             0
Call_Timestamp                      0
Patient_Age                         0
Patient_Gender                      0
State                               0
Language                            0
New_or_Existing_Patient             0
Call_Channel                        0
Caller_Relationship                 0
Chief_Complaint                     0
Symptoms_Reported                   0
Symptom_Severity                    0
Duration_of_Symptoms_Days           0
Pain_Score                          0
Emergency_Flag                      0
Chronic_Condition                4194
Insurance_Type                      0
Preferred_Appointment_Urgency       0
Prior_Hospital_Visit_30D            0
Call_Duration_Minutes               0
Wait_Time_Minutes                   0
Repeat_Caller                       0
Sentiment                           0
Call_Transcript_Summary             0
Recommended_Department              0
dtype: int64
['Primary Care' 'Gastroenterology' 'Scheduling' 'Dermatology' 'Pediatrics'
 'OB-GYN' 'Billing' 'Nurse Triage' 'Cardiology' 'Urgent Care'
 'Emergency Department' 'Oncology' 'Mental Health' 'Neurology'
 'Pulmonology' 'Pharmacy' 'Orthopedics']
Recommended_Department
Emergency Department    1514
Primary Care            1185
Pediatrics               759
Nurse Triage             743
Gastroenterology         690
Urgent Care              644
Orthopedics              629
Pulmonology              487
Cardiology               421
Mental Health            420
Neurology                402
OB-GYN                   382
Oncology                 354
Dermatology              349
Scheduling               348
Billing                  341
Pharmacy                 332
Name: count, dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df = df.drop(columns=['Call_ID', 'Call_Timestamp', 'State', 'Language', 'New_or_Existing_Patient', 'Call_Channel', 'Caller_Relationship', 'Call_Duration_Minutes', 'Wait_Time_Minutes', 'Repeat_Caller', 'Sentiment'])

In [8]:
df

,Patient_Age,Patient_Gender,Chief_Complaint,Symptoms_Reported,Symptom_Severity,Duration_of_Symptoms_Days,Pain_Score,Emergency_Flag,Chronic_Condition,Insurance_Type,Preferred_Appointment_Urgency,Prior_Hospital_Visit_30D,Call_Transcript_Summary,Recommended_Department
0,33,Female,Needs to see a doctor and agent every,mild fever; blood pressure follow-up; general ...,High,10,9,No,Hypertension,Medicaid,Immediate,Yes,Caller reached the hospital call center genera...,Primary Care
1,27,Male,"Caller reports abdominal pain, vomiting",abdominal pain; vomiting; acid reflux,Low,21,6,No,NaN,Private,Routine,No,Family member called the access center stomach...,Gastroenterology
2,38,Male,"Caller reports needs specialist slot, book app...",needs specialist slot; book appointment,Medium,14,3,No,NaN,Private,Routine,No,Caller reached the hospital call center appoin...,Scheduling
3,7,Female,"Patient is dealing with skin lesion, acne flare",skin lesion; acne flare,Low,93,1,No,Multiple,Medicaid,Soon,No,Family member called the access center dermato...,Dermatology
4,17,Male,"Parent says child has fatigue, weight loss",fatigue; weight loss,Medium,83,3,No,Multiple,Private,Soon,Yes,Family member called the access center oncolog...,Pediatrics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,40,Female,Concern about wants nurse guidance,unclear pain; medication side effect,Low,8,6,No,NaN,Private,Soon,No,Inbound call received from patient unclear sym...,Nurse Triage
9996,33,Male,"Caller reports cough, vomiting",cough; vomiting,High,10,7,No,Heart Disease,Private,Same Day,No,Patient contacted the care line parent calling...,Gastroenterology
9997,40,Male,Possible life-threatening issue and exactly di...,heavy bleeding,Critical,0,7,Yes,Diabetes,Private,Immediate,No,Caller reached the hospital call center critic...,Emergency Department
9998,37,Male,"Caller reports abdominal pain, acid reflux",abdominal pain; acid reflux,Low,58,5,No,Multiple,Self-pay,Routine,No,Family member called the access center gastroi...,Gastroenterology
9999,44,Female,Patient is dealing with blood pressure follow-...,blood pressure follow-up; medication question;...,Low,91,2,No,NaN,Medicaid,Soon,No,Patient contacted the care line non-emergent s...,Primary Care

In [9]:
df = df.drop(columns=['Emergency_Flag','Chronic_Condition', 'Insurance_Type', 'Preferred_Appointment_Urgency', 'Prior_Hospital_Visit_30D', 'Call_Transcript_Summary'])

In [10]:
df

,Patient_Age,Patient_Gender,Chief_Complaint,Symptoms_Reported,Symptom_Severity,Duration_of_Symptoms_Days,Pain_Score,Recommended_Department
0,33,Female,Needs to see a doctor and agent every,mild fever; blood pressure follow-up; general ...,High,10,9,Primary Care
1,27,Male,"Caller reports abdominal pain, vomiting",abdominal pain; vomiting; acid reflux,Low,21,6,Gastroenterology
2,38,Male,"Caller reports needs specialist slot, book app...",needs specialist slot; book appointment,Medium,14,3,Scheduling
3,7,Female,"Patient is dealing with skin lesion, acne flare",skin lesion; acne flare,Low,93,1,Dermatology
4,17,Male,"Parent says child has fatigue, weight loss",fatigue; weight loss,Medium,83,3,Pediatrics
...,...,...,...,...,...,...,...,...
9995,40,Female,Concern about wants nurse guidance,unclear pain; medication side effect,Low,8,6,Nurse Triage
9996,33,Male,"Caller reports cough, vomiting",cough; vomiting,High,10,7,Gastroenterology
9997,40,Male,Possible life-threatening issue and exactly di...,heavy bleeding,Critical,0,7,Emergency Department
9998,37,Male,"Caller reports abdominal pain, acid reflux",abdominal pain; acid reflux,Low,58,5,Gastroenterology
9999,44,Female,Patient is dealing with blood pressure follow-...,blood pressure follow-up; medication question;...,Low,91,2,Primary Care

In [11]:
df.shape

(10000, 8)

In [12]:
df.columns.tolist()

['Patient_Age',
 'Patient_Gender',
 'Chief_Complaint',
 'Symptoms_Reported',
 'Symptom_Severity',
 'Duration_of_Symptoms_Days',
 'Pain_Score',
 'Recommended_Department']

In [13]:
df.dtypes

Patient_Age                   int64
Patient_Gender               object
Chief_Complaint              object
Symptoms_Reported            object
Symptom_Severity             object
Duration_of_Symptoms_Days     int64
Pain_Score                    int64
Recommended_Department       object
dtype: object

In [14]:
df.isnull().sum()

Patient_Age                  0
Patient_Gender               0
Chief_Complaint              0
Symptoms_Reported            0
Symptom_Severity             0
Duration_of_Symptoms_Days    0
Pain_Score                   0
Recommended_Department       0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.isna().sum()

Patient_Age                  0
Patient_Gender               0
Chief_Complaint              0
Symptoms_Reported            0
Symptom_Severity             0
Duration_of_Symptoms_Days    0
Pain_Score                   0
Recommended_Department       0
dtype: int64

In [17]:
df.describe()

        Patient_Age  Duration_of_Symptoms_Days    Pain_Score
count  10000.000000               10000.000000  10000.000000
mean      43.093500                  29.135200      4.478800
std       22.646873                  36.973461      2.801167
min        0.000000                   0.000000      0.000000
25%       26.000000                   5.000000      2.000000
50%       41.000000                  13.000000      5.000000
75%       59.000000                  42.000000      7.000000
max       95.000000                 180.000000     10.000000

In [18]:
df["Recommended_Department"].nunique()

17

In [19]:
df["Recommended_Department"].unique()

array(['Primary Care', 'Gastroenterology', 'Scheduling', 'Dermatology',
       'Pediatrics', 'OB-GYN', 'Billing', 'Nurse Triage', 'Cardiology',
       'Urgent Care', 'Emergency Department', 'Oncology', 'Mental Health',
       'Neurology', 'Pulmonology', 'Pharmacy', 'Orthopedics'],
      dtype=object)

In [20]:
df["Recommended_Department"].value_counts()

Recommended_Department
Emergency Department    1514
Primary Care            1185
Pediatrics               759
Nurse Triage             743
Gastroenterology         690
Urgent Care              644
Orthopedics              629
Pulmonology              487
Cardiology               421
Mental Health            420
Neurology                402
OB-GYN                   382
Oncology                 354
Dermatology              349
Scheduling               348
Billing                  341
Pharmacy                 332
Name: count, dtype: int64

In [21]:
(df["Chief_Complaint"].str.strip() == "").sum()

np.int64(0)

In [22]:
(df["Symptoms_Reported"].str.strip() == "").sum()

np.int64(0)

In [23]:
df["Patient_Gender"].value_counts()

Patient_Gender
Female    4956
Male      4770
Other      274
Name: count, dtype: int64

In [24]:
df["Symptom_Severity"].value_counts()

Symptom_Severity
Medium      3895
Low         2703
High        2523
Critical     879
Name: count, dtype: int64

In [25]:
df["Patient_Text"] = (
    "Chief Complaint: " + df["Chief_Complaint"] +
    ". Symptoms: " + df["Symptoms_Reported"]
)

In [26]:
df[["Chief_Complaint", "Symptoms_Reported", "Patient_Text"]].head()

,Chief_Complaint,Symptoms_Reported,Patient_Text
0,Needs to see a doctor and agent every,mild fever; blood pressure follow-up; general ...,Chief Complaint: Needs to see a doctor and age...
1,"Caller reports abdominal pain, vomiting",abdominal pain; vomiting; acid reflux,Chief Complaint: Caller reports abdominal pain...
2,"Caller reports needs specialist slot, book app...",needs specialist slot; book appointment,Chief Complaint: Caller reports needs speciali...
3,"Patient is dealing with skin lesion, acne flare",skin lesion; acne flare,Chief Complaint: Patient is dealing with skin ...
4,"Parent says child has fatigue, weight loss",fatigue; weight loss,Chief Complaint: Parent says child has fatigue...

In [27]:
df = df.drop(columns=["Chief_Complaint", "Symptoms_Reported"])

In [28]:
df.to_csv('../dataset/processed_data.csv', index=False)


print("processed_data.csv is created successfully")

processed_data.csv is created successfully